# Generated by Django 5.2.3 on 2025-06-20 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkin',
            options={'verbose_name': '习惯记录', 'verbose_name_plural': '习惯记录'},
        ),
        migrations.RenameField(
            model_name='habit',
            old_name='target_days',
            new_name='goal',
        ),
        migrations.RenameField(
            model_name='habit',
            old_name='current_streak',
            new_name='streak',
        ),
        migrations.RemoveField(
            model_name='badge',
            name='color',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='category',
        ),
        migrations.AddField(
            model_name='habit',
            name='icon',
            field=models.ImageField(blank=True, default='habits/default.png', upload_to='habits/', verbose_name='习惯图标'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='icon',
            field=models.ImageField(blank=True, default='badges/default.png', upload_to='badges/', verbose_name='徽章图标'),
        ),
        migrations.CreateModel(
            name='BadgeRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True, verbose_name='解锁时间')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badge_records', to='users.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badge_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
