# Generated by Django 5.2.3 on 2025-06-20 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_checkin_options_rename_target_days_habit_goal_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badgerecords',
            options={'verbose_name': '徽章记录', 'verbose_name_plural': '徽章记录'},
        ),
        migrations.RemoveField(
            model_name='habit',
            name='streak',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='total_checkins',
        ),
        migrations.AddField(
            model_name='checkin',
            name='streak',
            field=models.IntegerField(default=0, verbose_name='当前连续打卡'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='total_checkins',
            field=models.IntegerField(default=0, verbose_name='总打卡次数'),
        ),
        migrations.AlterUniqueTogether(
            name='badgerecords',
            unique_together={('user', 'badge')},
        ),
    ]
