# Generated by Django 5.2.3 on 2025-06-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_badgerecords_options_remove_habit_streak_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='打卡日期'),
        ),
    ]
