# Generated by Django 5.2.3 on 2025-06-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_checkin_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgerecords',
            name='unlocked',
            field=models.BooleanField(default=False, verbose_name='是否解锁'),
        ),
    ]
