# Generated by Django 5.2.3 on 2025-06-23 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_userprofile_habit_streak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='habit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='users.habit'),
            preserve_default=False,
        ),
    ]
