# Generated by Django 5.2.3 on 2025-06-23 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_badge_habit_habit_badge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='badge',
        ),
        migrations.AddField(
            model_name='habit',
            name='badges',
            field=models.ManyToManyField(blank=True, to='users.badge', verbose_name='解锁徽章'),
        ),
    ]
