# Generated by Django 5.2.3 on 2025-06-23 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_habit_badge_habit_badges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='badges',
        ),
        migrations.AddField(
            model_name='habit',
            name='badge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habits', to='users.badge', verbose_name='关联的徽章'),
        ),
    ]
