# Generated by Django 5.2.3 on 2025-06-23 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_habit_badges_habit_badge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='badge',
        ),
        migrations.AddField(
            model_name='badge',
            name='habit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='users.habit', verbose_name='习惯'),
            preserve_default=False,
        ),
    ]
