# Generated by Django 5.2.3 on 2025-06-19 09:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=10, verbose_name='性别')),
                ('pickup_location', models.CharField(max_length=200, verbose_name='接送地点')),
                ('birthdate', models.DateField(verbose_name='出生日期')),
                ('hometown', models.CharField(max_length=100, verbose_name='籍贯')),
                ('blood_type', models.CharField(blank=True, choices=[('A', 'A型'), ('B', 'B型'), ('AB', 'AB型'), ('O', 'O型'), ('other', '其他/未知')], max_length=10, verbose_name='血型')),
                ('id_card', models.CharField(max_length=20, verbose_name='身份证号')),
                ('height', models.FloatField(validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(250)], verbose_name='身高(cm)')),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(200)], verbose_name='体重(kg)')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='电子邮箱')),
                ('hobbies', models.CharField(blank=True, max_length=200, verbose_name='兴趣爱好')),
                ('specialty', models.CharField(blank=True, max_length=200, verbose_name='个人专长')),
                ('school_class', models.CharField(max_length=200, verbose_name='学校及班级')),
                ('camp_type', models.CharField(choices=[('15天训练营', '15天训练营'), ('15天将帅营', '15天将帅营'), ('30天训练营', '30天训练营'), ('30天将帅营', '30天将帅营'), ('45天训练营', '45天训练营'), ('45天将帅营', '45天将帅营')], max_length=50, verbose_name='训练营类型')),
                ('camp_date', models.DateField(blank=True, null=True, verbose_name='入营日期')),
                ('special_notes', models.TextField(blank=True, verbose_name='特殊说明')),
                ('guardian_name', models.CharField(max_length=100, verbose_name='监护人姓名')),
                ('guardian_workplace', models.CharField(blank=True, max_length=200, verbose_name='工作单位')),
                ('guardian_id_card', models.CharField(max_length=20, verbose_name='监护人身份证号')),
                ('guardian_phone', models.CharField(max_length=20, verbose_name='监护人电话')),
                ('relationship', models.CharField(choices=[('父亲', '父亲'), ('母亲', '母亲'), ('祖父', '祖父'), ('祖母', '祖母'), ('外祖父', '外祖父'), ('外祖母', '外祖母'), ('其他亲属', '其他亲属'), ('其他', '其他')], max_length=20, verbose_name='与营员关系')),
                ('emergency_phone', models.CharField(max_length=20, verbose_name='紧急联系电话')),
                ('address', models.CharField(max_length=300, verbose_name='家庭住址')),
                ('postal_code', models.CharField(max_length=10, verbose_name='邮政编码')),
                ('region', models.CharField(max_length=100, verbose_name='所属区域')),
                ('signature', models.CharField(max_length=100, verbose_name='监护人签名')),
                ('sign_date', models.DateField(verbose_name='签名日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '夏令营报名信息',
                'verbose_name_plural': '夏令营报名信息',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='问题内容')),
                ('category', models.CharField(choices=[('communication', '沟通技巧'), ('discipline', '纪律与规则'), ('emotion', '情绪管理'), ('education', '学习教育'), ('values', '价值观培养')], max_length=20, verbose_name='问题类别')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='答案解析')),
            ],
            options={
                'verbose_name': '问卷题目',
                'verbose_name_plural': '问卷题目',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=200, verbose_name='选项内容')),
                ('is_correct', models.BooleanField(default=False, verbose_name='是否正确')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='survey.question')),
            ],
            options={
                'verbose_name': '题目选项',
                'verbose_name_plural': '题目选项',
            },
        ),
    ]
